server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**,/api/v1/user/**,/swagger-ui/**,/v3/api-docs/**,/api/v1/admin/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/vi/restaurants/**
          filters:
            - name: AuthenticationFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: AuthenticationFilter
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: AuthenticationFilter





management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


