server:
  port: ${SERVER_PORT:9090}

eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}

spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:user?createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Emami@4321}

  jpa:
    show-sql: true

  flyway:
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rakeshsur72@gmail.com
    password: jxuh tbdm bziw hezf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis: localhost
    port: 6379

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

otp:
  expiry:
    minutes: 5

password:
  reset:
    token:
      expiry:
        minutes: 15

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

#cloud:
#  aws:
#    credentials:
#      access-key:
#      secret-key:
#    region:
#      static:
